#!/usr/bin/env bash
# Pure Homebrew formula renderer for scripts/update-formula.sh. Sourced.
# Echoes the full Formula/downprint.rb contents. No side effects.

# render_formula <owner> <version> <base_url> <d_amd64> <d_arm64> <l_amd64> <l_arm64>
render_formula() {
  local owner=$1 version=$2 base=$3 da=$4 dr=$5 la=$6 lr=$7
  cat <<RB
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh. DO NOT EDIT.
class Downprint < Formula
  desc "Convert Markdown to PDF with GitHub-like styling via headless Chrome"
  homepage "https://github.com/${owner}/downprint"
  version "${version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "${base}/downprint_darwin_amd64.tar.gz"
      sha256 "${da}"
    end
    if Hardware::CPU.arm?
      url "${base}/downprint_darwin_arm64.tar.gz"
      sha256 "${dr}"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "${base}/downprint_linux_amd64.tar.gz"
      sha256 "${la}"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${base}/downprint_linux_arm64.tar.gz"
      sha256 "${lr}"
    end
  end

  def install
    bin.install "downprint"
  end

  # A formula cannot depend on a cask, so the browser is left to the user.
  def caveats
    <<~EOS
      downprint needs Google Chrome or Chromium at runtime:
        brew install --cask google-chrome
      To use a browser outside the standard locations, set DOWNPRINT_CHROME
      or pass -chrome /path/to/browser.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/downprint -version")
  end
end
RB
}
